name: dr_skin
description: A skin disease diagnosis and educational app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^0.8.9
  path_provider: ^2.0.15
  shared_preferences: ^2.0.15
  provider: ^6.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12
  google_fonts: ^5.1.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/ 